"""empty message

Revision ID: 5dbd016beba7
Revises: 103da3333706
Create Date: 2025-08-05 13:21:56.638774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbd016beba7'
down_revision = '103da3333706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_if', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_if_user'), 'user', ['user_if'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_user_if_user'), type_='foreignkey')
        batch_op.drop_column('user_if')

    # ### end Alembic commands ###
